#!/usr/bin/env python3
"""Using the turtle graphics module"""

from turtle import Turtle, Screen

t = Turtle()
t.shape("turtle")
t.color("red")

# Draw a triangle
for _ in range(3):
    t.forward(100)
    t.left(120)

# screen object: should be instantiated at the end of the program
screen = Screen()
screen.exitonclick()
